# Generated by Django 6.0.3 on 2026-03-07 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plataforma', models.CharField(choices=[('MEET', 'Google Meet'), ('ZOOM', 'Zoom'), ('WHATSAPP', 'WhatsApp Video'), ('OTRO', 'Otro / Teléfono')], default='MEET', max_length=20)),
                ('enlace_reunion', models.URLField(blank=True, help_text='URL o enlace para unirse a la teleconsulta', max_length=500, null=True)),
                ('codigo_acceso', models.CharField(blank=True, help_text='Contraseña o PIN (Opcional)', max_length=50, null=True)),
                ('estado_conexion', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('EN_CURSO', 'En Curso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PROGRAMADA', max_length=20)),
                ('notas_preliminares', models.TextField(blank=True, help_text='Síntomas reportados antes de entrar a sesión', null=True)),
                ('cita', models.OneToOneField(limit_choices_to={'tipo': 'CONSULTA'}, on_delete=django.db.models.deletion.CASCADE, related_name='consulta_virtual', to='agenda.cita')),
            ],
            options={
                'verbose_name': 'Consulta Virtual',
                'verbose_name_plural': 'Consultas Virtuales',
            },
        ),
    ]
