const router = require('express').Router();
const auth   = require('../middlewares/auth');
const ctrl        = require('../controllers/clientesController');
const fichaCtrl   = require('../controllers/fichaClienteController');
router.use(auth);
router.get('/',                   ctrl.listar);
router.get('/:id/ficha',          fichaCtrl.ficha);
router.get('/:id',                ctrl.obtener);
router.post('/',                  ctrl.crear);
router.put('/:id',                ctrl.actualizar);
router.delete('/:id',             ctrl.eliminar);
router.post('/:id/portal-token',  ctrl.generarPortalToken);
module.exports = router;
