# Generated by Django 6.0.3 on 2026-03-07 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(default='VetSystem', max_length=150)),
                ('slogan', models.CharField(blank=True, max_length=200, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracion/')),
                ('simbolo_moneda', models.CharField(default='S/', help_text='Ej: S/, $, €, Bs.', max_length=10)),
                ('nombre_moneda', models.CharField(blank=True, default='Soles', max_length=50)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True, verbose_name='RUC / RIF / NIT')),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono2', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono alternativo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', models.CharField(blank=True, default='Perú', max_length=100)),
                ('color_primario', models.CharField(default='#0bb8c8', help_text='Color hexadecimal Ej: #0bb8c8', max_length=7)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuración',
            },
        ),
    ]
