# Generated by Django 6.0.3 on 2026-03-06 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('motivo_consulta', models.TextField()),
                ('anamnesis', models.TextField(help_text='Antecedentes y sintomatología reportada')),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('frecuencia_respiratoria', models.IntegerField(blank=True, null=True)),
                ('mucosas', models.CharField(blank=True, max_length=50, null=True)),
                ('tiempo_llenado_capilar', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('proxima_cita', models.DateField(blank=True, null=True)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agenda.cita')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_clinicas', to='clientes.mascota')),
                ('veterinario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicaciones_generales', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('historia_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='medico.historiaclinica')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=100)),
                ('dosis', models.CharField(max_length=100)),
                ('frecuencia', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField(default=1)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='medico.receta')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_vacuna', models.CharField(max_length=100)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_aplicacion', models.DateField()),
                ('fecha_proxima_dosis', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='clientes.mascota')),
                ('producto', models.ForeignKey(limit_choices_to={'categoria__nombre__icontains': 'vacuna'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto')),
                ('veterinario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
