# Generated by Django 6.0.3 on 2026-03-06 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agenda', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioGrooming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bano', models.BooleanField(default=False, verbose_name='Baño')),
                ('corte_pelo', models.BooleanField(default=False, verbose_name='Corte de Pelo')),
                ('corte_unas', models.BooleanField(default=False, verbose_name='Corte de Uñas')),
                ('limpieza_oidos', models.BooleanField(default=False, verbose_name='Limpieza de Oídos')),
                ('glandulas', models.BooleanField(default=False, verbose_name='Cepillado Glándulas Anales')),
                ('perfume', models.BooleanField(default=False, verbose_name='Perfume/Lazo')),
                ('observaciones', models.TextField(blank=True, help_text='Ej: Presencia de pulgas, alergias de piel', null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grooming', to='agenda.cita')),
                ('peluquero', models.ForeignKey(limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
