# Generated by Django 6.0.3 on 2026-03-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grooming', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciogrooming',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
