# Generated by Django 6.0.3 on 2026-03-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Veterinaria', max_length=150)),
                ('razon_social', models.CharField(blank=True, max_length=150, null=True)),
                ('ruc', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clinica/')),
                ('color_primario', models.CharField(default='#0bb8c8', help_text='Color teal del sidebar', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Datos de la Clínica',
            },
        ),
    ]
